parameters:
#    symfonyse_author.example.class: Symfonyse\AuthorBundle\Example

services:
  symfonyse.author.content_provider:
    class: Symfonyse\AuthorBundle\ContentProvider\ContentProvider
    arguments: [~ , 'md']
    calls:
      - [setContentProviders, [[@symfonyse.blog.content_provider, @symfonyse.video.content_provider, @symfonyse.event.content_provider]]]

  symfonyse.author.service.photo:
    class: Symfonyse\AuthorBundle\Service\PhotoService
    arguments: [@kernel]

  symfonyse.core.twig.author_extension:
    class: Symfonyse\AuthorBundle\Twig\AuthorExtension
    arguments: [@symfonyse.author.service.photo]
    tags:
      - { name: twig.extension }