homepage:
  path:  /
  defaults: { _controller: "SymfonyseContentBundle:Default:homepage" }
  methods: [GET]

page:
  path:  /page/{permalink}
  defaults: { _controller: "SymfonyseContentBundle:Page:page" }
  methods: [GET]
  requirements:
    permalink:  .+