event_index:
  path:  /esi/index
  defaults: { _controller: "SymfonyseEventBundle:Event:index" }
  methods: [GET]

event_next:
  path:  /esi/next-event
  defaults: { _controller: "SymfonyseEventBundle:Event:nextEvent" }
  methods: [GET]

event:
  path:  /{permalink}
  defaults: { _controller: "SymfonyseEventBundle:Event:entry" }
  methods: [GET]
  requirements:
    permalink:  "[0-9]+/.+"