parameters:
    symfonyse.event.meetup_group_name: symfony-se

services:
  symfonyse.event.file_content_provider:
    class: Symfonyse\EventBundle\ContentProvider\FileContentProvider
    arguments: [~ , 'md']


  symfonyse.event.content_provider:
    class: Symfonyse\EventBundle\ContentProvider\MeetupContentProvider
    arguments: [@dms_meetup_api.client_factory, %symfonyse.event.meetup_group_name%]


