blog_index:
  path:  /index
  defaults: { _controller: "SymfonyseBlogBundle:Blog:index" }
  methods: [GET]

blog:
  path:  /{permalink}
  defaults: { _controller: "SymfonyseBlogBundle:Blog:entry" }
  methods: [GET]
  requirements:
    permalink:  "[0-9]+/.+"