parameters:
#    symfonyse_tag.example.class: Symfonyse\TagBundle\Example

services:
  symfonyse.tag.content_provider:
    class: Symfonyse\TagBundle\ContentProvider\ContentProvider
    arguments: [~ , 'md']
    calls:
      - [setContentProviders, [["@symfonyse.blog.content_provider", "@symfonyse.video.content_provider", "@symfonyse.event.content_provider"]]]
