video_index:
  path:  /index
  defaults: { _controller: "SymfonyseVideoBundle:Video:index" }
  methods: [GET]

video:
  path:  /{permalink}
  defaults: { _controller: "SymfonyseVideoBundle:Video:entry" }
  methods: [GET]
  requirements:
    permalink:  .+
