parameters:
#    symfonyse_video.example.class: Symfonyse\VideoBundle\Example

services:
  symfonyse.video.content_provider:
    class: Symfonyse\VideoBundle\ContentProvider\ContentProvider
    arguments: [~ , 'md']